Updated allowed actions for generate-docker-image-tags

diff --git a/generate-docker-image-tags/action.yml b/generate-docker-image-tags/action.yml
--- a/generate-docker-image-tags/action.yml
+++ b/generate-docker-image-tags/action.yml
@@ -38,11 +38,11 @@ runs:
         if [ "$GITHUB_EVENT_NAME" == "pull_request" ]
         then
           BRANCH=$GITHUB_HEAD_REF
-        elif [ "$GITHUB_EVENT_NAME" == "push" ]
+        elif [ "$GITHUB_EVENT_NAME" == "push" ] || [ "$GITHUB_EVENT_NAME" == "release" ]
         then
           BRANCH=${GITHUB_REF##*/}
         else
-          printf 'Cannot determine tags: Workflow must be triggered by "push" or "pull_request" event.' && exit 1
+          printf 'Cannot determine tags: Workflow must be triggered by "push", "pull_request", or "release" event.' && exit 1
         fi
 
         printf "::set-output name=branch::$BRANCH"
